Gossip_app/config/routes.rb
Rails.application.routes.draw do
	resources :gossips
	resources :home
  get 'user/:id_user', to: 'user#show'
  root 'home#index'
  get 'welcome/:id', to:'welcome#welcome_page'
  get 'static_pages/contact', to: 'static_pages#contact'

  get 'static_pages/team', to: 'static_pages#team'
end

Gossip_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Gossip_app/app/models/city.rb
class City < ApplicationRecord

	#LINKS PART
  has_many :users

  #VALIDATIONS PART
  validates :name,
  presence: true

  validates :zip_code,
  presence: true

end

Gossip_app/app/models/gossip.rb
class Gossip < ApplicationRecord

	#LINKS PART
  belongs_to :user
  has_many :tag_gossip_links
  has_many :tags, through: :tag_gossip_links


  	#VALIDATION PART
  validates :title,
  	presence: true,
  	length: {in: 3..14}

  validates :content,
  	presence: true


end

Gossip_app/app/models/private_message.rb
class PrivateMessage < ApplicationRecord

	#LINKS PART
  belongs_to :sender, class_name: "User"
  has_many :recipient_to_pm_links, foreign_key: 'received_message_id'
  has_many :recipients, foreign_key: 'recipient_id', class_name: "User", through: :recipient_to_pm_links

  #VALIDATIONS PART
  validates :sender_id,
  presence: true


end

Gossip_app/app/models/recipient_to_pm_link.rb
class RecipientToPmLink < ApplicationRecord
  
	#LINKS
  belongs_to :recipient, class_name: "User"
  belongs_to :received_message, class_name: "PrivateMessage"

  	#VALIDATION PART

end

Gossip_app/app/models/tag.rb
class Tag < ApplicationRecord

	#LINKS PART
  has_many :tag_gossip_links
  has_many :gossips, through: :tag_gossip_links

  #VALIDATIONS PARTS
  validates :title,
  presence: true
  
end

Gossip_app/app/models/tag_gossip_link.rb
class TagGossipLink < ApplicationRecord

	#LINKS PART
  belongs_to :gossip
  belongs_to :tag

  	#VALIDATIONS PART
  validates :gossip_id,
  presence: true,
  


end

Gossip_app/app/models/user.rb
class User < ApplicationRecord

	#LINKS PART
  belongs_to :city
  has_many :gossips
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :recipient_to_pm_links, foreign_key: 'recipient_id'
  has_many :received_messages, foreign_key: 'received_message_id', class_name: "PrivateMessage", through: :recipient_to_pm_links


  	#VALIDATIONS PART
  validates :first_name,
  presence: true

  validates :last_name,
  presence: true

  validates :email,
  presence: true,
  format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please" }

end

Gossip_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

Gossip_app/app/controllers/gossips_controller.rb
class GossipsController < ApplicationController

	def create
		@gossip = Gossip.new(title: params[:title], content: params[:content])

		if @gossip.save
			#render "home/index"
		else
			
		end
	end

  	def show
  		@gossip = Gossip.find(params[:id])
  	end

  	def edit
  		
  	end

  	def new
  		
  	end

end

Gossip_app/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@gossip = Gossip.all
  end
end

Gossip_app/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def contact
  end

  def team
  end
  
end

Gossip_app/app/controllers/user_controller.rb
class UserController < ApplicationController
  def show
  	@user = User.find(params[:id_user])
  end
end

Gossip_app/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def welcome_page
  	 @user = User.find(params[:id])
  end
end

Gossip_app/app/helpers/application_helper.rb
module ApplicationHelper
end

Gossip_app/app/helpers/gossip_helper.rb
module GossipHelper
end

Gossip_app/app/helpers/home_helper.rb
module HomeHelper
end

Gossip_app/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

Gossip_app/app/helpers/user_helper.rb
module UserHelper
end

Gossip_app/app/helpers/welcome_helper.rb
module WelcomeHelper
end

Gossip_app/app/views/gossip/show.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Gossip details</title>
</head>
<body>


	<div class="container text-center" style="margin-top: 30px">
		<h3 style="color: red;">Gossip n°<%= @gossip.id %></h3>
		<br/>
		<h3>Title : <%= @gossip.title %></h3>
		<h4><a href="../user/<%=@gossip.user.id%>">Author : <%= @gossip.user.first_name%></a></h4>
		<br/>
		<h4 class="text-center" style="max-width: 60%; margin: auto;"><em><%=@gossip.content%></em></h4>
		<br/>
		<br/>
		<h6>Created at :<%=@gossip.created_at%></em></h6>

	<div>

</body>
</html>

Gossip_app/app/views/gossips/new.html.erb
<html>
  <body>
    <!-- ... -->

    <%= form_tag url_for(action: 'create'), method: "post" do %>

      <%= label_tag 'Title' %>
      <%= text_field_tag 'title', @title %>
      <br /> <br />

      <%= label_tag 'Content' %>
      <%= text_area_tag 'content', @content %>
      <br /> <br />

      <%= submit_tag "Create Gossip" %>

    <% end %>

    <!-- ... -->
  </body>
</html>

Gossip_app/app/views/gossips/show.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Gossip details</title>
</head>
<body>


	<div class="container text-center" style="margin-top: 30px">
		<h3 style="color: red;">Gossip n°<%= @gossip.id %></h3>
		<br/>
		<h3>Title : <%= @gossip.title %></h3>
		<h4><a href="../user/<%=@gossip.user.id%>">Author : <%= @gossip.user.first_name%></a></h4>
		<br/>
		<h4 class="text-center" style="max-width: 60%; margin: auto;"><em><%=@gossip.content%></em></h4>
		<br/>
		<br/>
		<h6>Created at :<%=@gossip.created_at%></em></h6>
		<h7><a href="../gossips/<%=@gossip.id%>/edit" >Modify this gossip</a></h7>

	<div>

</body>
</html>

Gossip_app/app/views/home/home_page.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>

<div class="container text-center" style="margin-top: 30px;">
	<h1>Welcome to The Gossip Project</h1>
	<br/>
	<h2>Here is the list of all Gossips:</h2>
	<br/>
</div>



	<div class="container d-flex flex-wrap justify-content-center" style="max-width: 100%">

		<% @gossip.each do |gossip| %>



		<div class="col-md-3" style="margin: 30px 30px 30px 30px;">
			<div class="card" style="width: 18rem; height: auto;">
				<img class="card-img-top" src="/Gossip.jpg" alt="Card image cap">
				<div class="card-body">
					<h5 class="card-title"><span style="color: red">Gossip n°<%= gossip.id%></span> : <%=gossip.title%></h5>
					<p class="card-text">Author : <%=gossip.user.first_name%><br/>
						Description : <%=gossip.content%></p>
						<a href="gossip/<%= gossip.id%>" class="btn btn-primary">Know more</a>
					</div>
				</div>
			</div>

			<%end%>
		</div>

	</body>
	</html>

Gossip_app/app/views/home/index.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>

<div class="container text-center" style="margin-top: 30px;">
	<h1>Welcome to The Gossip Project</h1>
	<br/>
	<h2><a href="../gossips/new">Click here to create a new gossip</a></h2>
	<br/>
	<h2>Here is the list of all Gossips:</h2>
	<br/>
</div>



	<div class="container d-flex flex-wrap justify-content-center" style="max-width: 100%">

		<% @gossip.each do |gossip| %>



		<div class="col-md-3" style="margin: 30px 30px 30px 30px;">
			<div class="card" style="width: 18rem; height: auto;">
				<img class="card-img-top" src="/Gossip.jpg" alt="Card image cap">
				<div class="card-body">
					<h5 class="card-title"><span style="color: red">Gossip n°<%= gossip.id%></span> : <%=gossip.title%></h5>
					<p class="card-text">Author : <%=gossip.user.first_name%><br/>
						Description : <%=gossip.content%></p>
						<a href="gossips/<%= gossip.id%>" class="btn btn-primary">Know more</a>
					</div>
				</div>
			</div>

			<%end%>
		</div>

	</body>
	</html>

Gossip_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>TheGossipProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <!-- NAV BAR -->
  <nav class="navbar navbar-expand-lg navbar-light bg-light" style="background-color: #303030 !important">
    <a class="navbar-brand font_white" href="#">The Gossip Project</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link font_white" href="<%=root_path%>">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link font_white" href="<%=static_pages_contact_path%>">Contact</a>
        </li>
        <li class="nav-item">
          <a class="nav-link font_white" href="<%=static_pages_team_path %>">Team</a>
        </li>
      </ul>
      <span class="navbar-text font_white">
        Welcome to The Gossip Project
      </span>
    </div>
  </nav>
  <!-- FIN NAV BAR -->
    <%= yield %>
  </body>
</html>

<style>
.font_white{
  color: white !important;
}
</style>

Gossip_app/app/views/static_pages/contact.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Contact</title>
</head>
<body>
	<h3 class="text-center" style="margin-top: 30px;">Contact</h3>
	<p class="text-center">email : email@email.com</p>
</body>
</html>

Gossip_app/app/views/static_pages/team.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Team</title>
</head>
<body>
	<h3 class="text-center" style="margin-top: 30px;">Here is the team :</h3>
	<br/>
	<p class="text-center">Léo Wsjdsjdsd</p>
	<p class="text-center">Lionel Forest</p>
	<p class="text-center">Baptiste Veyrard</p>

</body>
</html>

Gossip_app/app/views/user/show.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Gossip details</title>
</head>
<body>


	<div class="container" style="margin-top: 30px">
		<h2><%=@user.first_name%> <%=@user.last_name%></h2>
		<br/>
		<img src="/Face.jpg" alt="Face">
		<br/>
		<h4 style="margin-top: 20px;">My information:</h4>
		<br/>
		<h5><strong>My age :</strong> <%=@user.age%></h5>
		<h5><strong>My email :</strong> <%=@user.email%></h5>
		<h5><strong>My description :</strong> <%=@user.description%></h5>
		<h5><strong>Created gossips :</strong> <%=@user.gossips.count%></h5>
		<br/>
		<br/>
		<div>

		</body>
		</html>

Gossip_app/app/views/welcome/welcome_page.html.erb
<h1>Welcome <%= @user.first_name %> <%= @user.last_name %></h1>
<p>Find me in app/views/welcome/welcome.html.erb</p>